# This is a basic workflow to help you get started with Actions

name: Temporal Test

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
   start_date:
    description: 'The start date in yyyy-MM-dd'
    required: true
    type: string
   end_date:
    description: 'The end date in yyyy-MM-dd'
    required: true
    type: string
   namespace:
    description: 'The temporal namespace to execute against'
    required: true
    type: choice
    options:
     - customer-migration-tms-dev.wpg6u
     - customer-migration-tms-pnv.wpg6u
     - customer-migration-tms-sitk.wpg6u
     - customer-migration-tms-sitl.wpg6u
     - customer-migration-tms-sitq.wpg6u
     - customer-migration-tms-prod.wpg6u

jobs:
 run-workflow:
  runs-on: ubuntu-latest
  steps:
   - name: Install Temporal CLI
     uses: temporalio/setup-temporal@v0
   - name: Run workflow
     run: |
      temporal workflow start --task-queue TESTING_QUEUE \
      --type UpdateCustomerProfile --input '{"capCisID":"1232432", "migrationDate":"${{ inputs.start_date }}"}' \
      --workflow-id $(uuidgen | tr "[:upper:]" "[:lower:]") \
      --namespace customer-migration-tms-sitl.wpg6u \
